# 基础配置文件

spring:
  profiles:
    active: dev     # 配置文件环境
  http:
    encoding:
      force: true
      charset: utf-8
      enabled: true
  mvc:
    throw-exception-if-no-handler-found: true     # 接口404时抛出异常
  resources:
    add-mappings: false

server:
  servlet:
    context-path: /v1     # 应用路径，可以通过设置路径来控制版本
  tomcat:
    uri-encoding: UTF-8

ea:
  mussel:
    enabled: true
    env: boe
    app-id: 6982a64d-3be9-4603-913f-00b7da59f530
    secret: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQC3NNb04K6IjFtws/9ITvUCRAEbdIOeCfN4+K+0Fjw5KVUqYhd8N77AEUwuLxS9OKyzMcngwSnbisP67blWpx7XAArmXX5VX13akUJwb49V3vthLv+kFroEWVIrn8og5SL1sLRQGuKnXfKz4pFeWbJzf+J8BMh6WhVhFcfqJx527QIDAQAB
    tos-channel-id:
      - tos_7257724733393862956